// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Equipment is the predicate function for equipment builders.
type Equipment func(*sql.Selector)

// Idea is the predicate function for idea builders.
type Idea func(*sql.Selector)

// Ingredient is the predicate function for ingredient builders.
type Ingredient func(*sql.Selector)

// Instruction is the predicate function for instruction builders.
type Instruction func(*sql.Selector)

// Nutrition is the predicate function for nutrition builders.
type Nutrition func(*sql.Selector)

// Product is the predicate function for product builders.
type Product func(*sql.Selector)

// Recipe is the predicate function for recipe builders.
type Recipe func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)

// Tag is the predicate function for tag builders.
type Tag func(*sql.Selector)
