// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/tinygodsdev/tinycooksweb/pkg/storage/entstorage/ent/idea"
	"github.com/tinygodsdev/tinycooksweb/pkg/storage/entstorage/ent/recipe"
)

// Idea is the model entity for the Idea schema.
type Idea struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// Text holds the value of the "text" field.
	Text string `json:"text,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the IdeaQuery when eager-loading is set.
	Edges        IdeaEdges `json:"edges"`
	recipe_ideas *uuid.UUID
	selectValues sql.SelectValues
}

// IdeaEdges holds the relations/edges for other nodes in the graph.
type IdeaEdges struct {
	// Recipe holds the value of the recipe edge.
	Recipe *Recipe `json:"recipe,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// RecipeOrErr returns the Recipe value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e IdeaEdges) RecipeOrErr() (*Recipe, error) {
	if e.Recipe != nil {
		return e.Recipe, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: recipe.Label}
	}
	return nil, &NotLoadedError{edge: "recipe"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Idea) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case idea.FieldText:
			values[i] = new(sql.NullString)
		case idea.FieldID:
			values[i] = new(uuid.UUID)
		case idea.ForeignKeys[0]: // recipe_ideas
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Idea fields.
func (i *Idea) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for j := range columns {
		switch columns[j] {
		case idea.FieldID:
			if value, ok := values[j].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[j])
			} else if value != nil {
				i.ID = *value
			}
		case idea.FieldText:
			if value, ok := values[j].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field text", values[j])
			} else if value.Valid {
				i.Text = value.String
			}
		case idea.ForeignKeys[0]:
			if value, ok := values[j].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field recipe_ideas", values[j])
			} else if value.Valid {
				i.recipe_ideas = new(uuid.UUID)
				*i.recipe_ideas = *value.S.(*uuid.UUID)
			}
		default:
			i.selectValues.Set(columns[j], values[j])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Idea.
// This includes values selected through modifiers, order, etc.
func (i *Idea) Value(name string) (ent.Value, error) {
	return i.selectValues.Get(name)
}

// QueryRecipe queries the "recipe" edge of the Idea entity.
func (i *Idea) QueryRecipe() *RecipeQuery {
	return NewIdeaClient(i.config).QueryRecipe(i)
}

// Update returns a builder for updating this Idea.
// Note that you need to call Idea.Unwrap() before calling this method if this Idea
// was returned from a transaction, and the transaction was committed or rolled back.
func (i *Idea) Update() *IdeaUpdateOne {
	return NewIdeaClient(i.config).UpdateOne(i)
}

// Unwrap unwraps the Idea entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (i *Idea) Unwrap() *Idea {
	_tx, ok := i.config.driver.(*txDriver)
	if !ok {
		panic("ent: Idea is not a transactional entity")
	}
	i.config.driver = _tx.drv
	return i
}

// String implements the fmt.Stringer.
func (i *Idea) String() string {
	var builder strings.Builder
	builder.WriteString("Idea(")
	builder.WriteString(fmt.Sprintf("id=%v, ", i.ID))
	builder.WriteString("text=")
	builder.WriteString(i.Text)
	builder.WriteByte(')')
	return builder.String()
}

// Ideas is a parsable slice of Idea.
type Ideas []*Idea
