// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tinygodsdev/tinycooksweb/pkg/storage/entstorage/ent/idea"
	"github.com/tinygodsdev/tinycooksweb/pkg/storage/entstorage/ent/recipe"
)

// IdeaCreate is the builder for creating a Idea entity.
type IdeaCreate struct {
	config
	mutation *IdeaMutation
	hooks    []Hook
}

// SetText sets the "text" field.
func (ic *IdeaCreate) SetText(s string) *IdeaCreate {
	ic.mutation.SetText(s)
	return ic
}

// SetID sets the "id" field.
func (ic *IdeaCreate) SetID(u uuid.UUID) *IdeaCreate {
	ic.mutation.SetID(u)
	return ic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ic *IdeaCreate) SetNillableID(u *uuid.UUID) *IdeaCreate {
	if u != nil {
		ic.SetID(*u)
	}
	return ic
}

// SetRecipeID sets the "recipe" edge to the Recipe entity by ID.
func (ic *IdeaCreate) SetRecipeID(id uuid.UUID) *IdeaCreate {
	ic.mutation.SetRecipeID(id)
	return ic
}

// SetNillableRecipeID sets the "recipe" edge to the Recipe entity by ID if the given value is not nil.
func (ic *IdeaCreate) SetNillableRecipeID(id *uuid.UUID) *IdeaCreate {
	if id != nil {
		ic = ic.SetRecipeID(*id)
	}
	return ic
}

// SetRecipe sets the "recipe" edge to the Recipe entity.
func (ic *IdeaCreate) SetRecipe(r *Recipe) *IdeaCreate {
	return ic.SetRecipeID(r.ID)
}

// Mutation returns the IdeaMutation object of the builder.
func (ic *IdeaCreate) Mutation() *IdeaMutation {
	return ic.mutation
}

// Save creates the Idea in the database.
func (ic *IdeaCreate) Save(ctx context.Context) (*Idea, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *IdeaCreate) SaveX(ctx context.Context) *Idea {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *IdeaCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *IdeaCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *IdeaCreate) defaults() {
	if _, ok := ic.mutation.ID(); !ok {
		v := idea.DefaultID()
		ic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *IdeaCreate) check() error {
	if _, ok := ic.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Idea.text"`)}
	}
	return nil
}

func (ic *IdeaCreate) sqlSave(ctx context.Context) (*Idea, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *IdeaCreate) createSpec() (*Idea, *sqlgraph.CreateSpec) {
	var (
		_node = &Idea{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(idea.Table, sqlgraph.NewFieldSpec(idea.FieldID, field.TypeUUID))
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ic.mutation.Text(); ok {
		_spec.SetField(idea.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if nodes := ic.mutation.RecipeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   idea.RecipeTable,
			Columns: []string{idea.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.recipe_ideas = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// IdeaCreateBulk is the builder for creating many Idea entities in bulk.
type IdeaCreateBulk struct {
	config
	err      error
	builders []*IdeaCreate
}

// Save creates the Idea entities in the database.
func (icb *IdeaCreateBulk) Save(ctx context.Context) ([]*Idea, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Idea, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*IdeaMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *IdeaCreateBulk) SaveX(ctx context.Context) []*Idea {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *IdeaCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *IdeaCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
