// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/tinygodsdev/tinycooksweb/pkg/storage/entstorage/ent/instruction"
	"github.com/tinygodsdev/tinycooksweb/pkg/storage/entstorage/ent/recipe"
)

// InstructionCreate is the builder for creating a Instruction entity.
type InstructionCreate struct {
	config
	mutation *InstructionMutation
	hooks    []Hook
}

// SetText sets the "text" field.
func (ic *InstructionCreate) SetText(s string) *InstructionCreate {
	ic.mutation.SetText(s)
	return ic
}

// SetOrder sets the "order" field.
func (ic *InstructionCreate) SetOrder(i int) *InstructionCreate {
	ic.mutation.SetOrder(i)
	return ic
}

// SetID sets the "id" field.
func (ic *InstructionCreate) SetID(u uuid.UUID) *InstructionCreate {
	ic.mutation.SetID(u)
	return ic
}

// SetNillableID sets the "id" field if the given value is not nil.
func (ic *InstructionCreate) SetNillableID(u *uuid.UUID) *InstructionCreate {
	if u != nil {
		ic.SetID(*u)
	}
	return ic
}

// SetRecipeID sets the "recipe" edge to the Recipe entity by ID.
func (ic *InstructionCreate) SetRecipeID(id uuid.UUID) *InstructionCreate {
	ic.mutation.SetRecipeID(id)
	return ic
}

// SetNillableRecipeID sets the "recipe" edge to the Recipe entity by ID if the given value is not nil.
func (ic *InstructionCreate) SetNillableRecipeID(id *uuid.UUID) *InstructionCreate {
	if id != nil {
		ic = ic.SetRecipeID(*id)
	}
	return ic
}

// SetRecipe sets the "recipe" edge to the Recipe entity.
func (ic *InstructionCreate) SetRecipe(r *Recipe) *InstructionCreate {
	return ic.SetRecipeID(r.ID)
}

// Mutation returns the InstructionMutation object of the builder.
func (ic *InstructionCreate) Mutation() *InstructionMutation {
	return ic.mutation
}

// Save creates the Instruction in the database.
func (ic *InstructionCreate) Save(ctx context.Context) (*Instruction, error) {
	ic.defaults()
	return withHooks(ctx, ic.sqlSave, ic.mutation, ic.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (ic *InstructionCreate) SaveX(ctx context.Context) *Instruction {
	v, err := ic.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (ic *InstructionCreate) Exec(ctx context.Context) error {
	_, err := ic.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ic *InstructionCreate) ExecX(ctx context.Context) {
	if err := ic.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ic *InstructionCreate) defaults() {
	if _, ok := ic.mutation.ID(); !ok {
		v := instruction.DefaultID()
		ic.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (ic *InstructionCreate) check() error {
	if _, ok := ic.mutation.Text(); !ok {
		return &ValidationError{Name: "text", err: errors.New(`ent: missing required field "Instruction.text"`)}
	}
	if _, ok := ic.mutation.Order(); !ok {
		return &ValidationError{Name: "order", err: errors.New(`ent: missing required field "Instruction.order"`)}
	}
	if v, ok := ic.mutation.Order(); ok {
		if err := instruction.OrderValidator(v); err != nil {
			return &ValidationError{Name: "order", err: fmt.Errorf(`ent: validator failed for field "Instruction.order": %w`, err)}
		}
	}
	return nil
}

func (ic *InstructionCreate) sqlSave(ctx context.Context) (*Instruction, error) {
	if err := ic.check(); err != nil {
		return nil, err
	}
	_node, _spec := ic.createSpec()
	if err := sqlgraph.CreateNode(ctx, ic.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	ic.mutation.id = &_node.ID
	ic.mutation.done = true
	return _node, nil
}

func (ic *InstructionCreate) createSpec() (*Instruction, *sqlgraph.CreateSpec) {
	var (
		_node = &Instruction{config: ic.config}
		_spec = sqlgraph.NewCreateSpec(instruction.Table, sqlgraph.NewFieldSpec(instruction.FieldID, field.TypeUUID))
	)
	if id, ok := ic.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := ic.mutation.Text(); ok {
		_spec.SetField(instruction.FieldText, field.TypeString, value)
		_node.Text = value
	}
	if value, ok := ic.mutation.Order(); ok {
		_spec.SetField(instruction.FieldOrder, field.TypeInt, value)
		_node.Order = value
	}
	if nodes := ic.mutation.RecipeIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   instruction.RecipeTable,
			Columns: []string{instruction.RecipeColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(recipe.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.recipe_instructions = &nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// InstructionCreateBulk is the builder for creating many Instruction entities in bulk.
type InstructionCreateBulk struct {
	config
	err      error
	builders []*InstructionCreate
}

// Save creates the Instruction entities in the database.
func (icb *InstructionCreateBulk) Save(ctx context.Context) ([]*Instruction, error) {
	if icb.err != nil {
		return nil, icb.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(icb.builders))
	nodes := make([]*Instruction, len(icb.builders))
	mutators := make([]Mutator, len(icb.builders))
	for i := range icb.builders {
		func(i int, root context.Context) {
			builder := icb.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*InstructionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, icb.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, icb.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, icb.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (icb *InstructionCreateBulk) SaveX(ctx context.Context) []*Instruction {
	v, err := icb.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (icb *InstructionCreateBulk) Exec(ctx context.Context) error {
	_, err := icb.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (icb *InstructionCreateBulk) ExecX(ctx context.Context) {
	if err := icb.Exec(ctx); err != nil {
		panic(err)
	}
}
